/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package fnln.andy.gpcp.ui;

import fnln.andy.gpcp.DBControl;
import fnln.andy.gpcp.core.Employee;
import fnln.andy.gpcp.core.PseudoDate;
import java.util.List;

/**
 *
 * @author andy
 */
public class AbsentEmployeesUi extends javax.swing.JDialog {

    /**
     * Creates new form AbsentEmployeesUi
     */
    public AbsentEmployeesUi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePanel = new javax.swing.JPanel();
        jDaySpinner = new javax.swing.JSpinner();
        jMonthComboBox = new javax.swing.JComboBox<>();
        jYearSpinner = new javax.swing.JSpinner();
        jDisplayAbsentEmployeesButton = new javax.swing.JButton();
        jTableScrollPane = new javax.swing.JScrollPane();
        jAbsentEmployeesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        jDaySpinner.setValue(1);
        jDatePanel.add(jDaySpinner);

        jMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre" }));
        jDatePanel.add(jMonthComboBox);

        jYearSpinner.setValue(2024);
        jDatePanel.add(jYearSpinner);

        getContentPane().add(jDatePanel);

        jDisplayAbsentEmployeesButton.setText("Afficher les employés absent pour cette date");
        jDisplayAbsentEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDisplayAbsentEmployeesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jDisplayAbsentEmployeesButton);

        jAbsentEmployeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro d'employé", "Nom de l'employé", "Prénom de l'employé", "Poste de l'employé", "Salaire de l'employé"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableScrollPane.setViewportView(jAbsentEmployeesTable);

        getContentPane().add(jTableScrollPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDisplayAbsentEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDisplayAbsentEmployeesButtonActionPerformed
        // TODO add your handling code here:
        final int day = (int)jDaySpinner.getValue();
        final int month = jMonthComboBox.getSelectedIndex() + 1;
        final int year = (int)jYearSpinner.getValue();
        
        PseudoDate date = new PseudoDate(day, month, year);
        
        List<Employee> toLoad = DBControl.deferEmployeeController().getAbsentEntries(date);
        
        DBControl.deferEmployeeController().reloadEntries(toLoad, jAbsentEmployeesTable);
    }//GEN-LAST:event_jDisplayAbsentEmployeesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbsentEmployeesUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbsentEmployeesUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbsentEmployeesUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbsentEmployeesUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AbsentEmployeesUi dialog = new AbsentEmployeesUi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jAbsentEmployeesTable;
    private javax.swing.JPanel jDatePanel;
    private javax.swing.JSpinner jDaySpinner;
    private javax.swing.JButton jDisplayAbsentEmployeesButton;
    private javax.swing.JComboBox<String> jMonthComboBox;
    private javax.swing.JScrollPane jTableScrollPane;
    private javax.swing.JSpinner jYearSpinner;
    // End of variables declaration//GEN-END:variables
}
