/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package fnln.andy.gpcp.ui;

import fnln.andy.gpcp.DBControl;
import fnln.andy.gpcp.core.DataArg;
import fnln.andy.gpcp.core.Employee;
import fnln.andy.gpcp.core.Util;

/**
 *
 * @author andy
 */
public class EmployeeFormUi extends javax.swing.JDialog {

    /**
     * Creates new form EmployeeFormUi
     */
    public EmployeeFormUi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEmployeeIdWrapperPanel = new javax.swing.JPanel();
        jEmployeeIdLabel = new javax.swing.JLabel();
        jEmployeeIdSpinner = new javax.swing.JSpinner();
        jEmployeeNameWrapperPanel = new javax.swing.JPanel();
        jEmployeeNameLabel = new javax.swing.JLabel();
        jEmployeeNameTextField = new javax.swing.JTextField();
        jEmployeeFirstNameWrapperPanel = new javax.swing.JPanel();
        jEmployeeFirstNameLabel = new javax.swing.JLabel();
        jEmployeeFirstNameTextField = new javax.swing.JTextField();
        jEmployeeJobWrapperPanel = new javax.swing.JPanel();
        jEmployeeJobLabel = new javax.swing.JLabel();
        jEmployeeJobTextField = new javax.swing.JTextField();
        jEmployeeSalaryWrapperPanel = new javax.swing.JPanel();
        jEmployeeSalaryLabel = new javax.swing.JLabel();
        jEmployeeSalarySpinner = new javax.swing.JSpinner();
        jButtonsWrapperPanel = new javax.swing.JPanel();
        jEmployeeConfirmButton = new javax.swing.JButton();
        jEmployeeResetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulaire d'un employé");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jEmployeeIdWrapperPanel.setLayout(new javax.swing.BoxLayout(jEmployeeIdWrapperPanel, javax.swing.BoxLayout.LINE_AXIS));

        jEmployeeIdLabel.setText("Numéro de l'employé(e):");
        jEmployeeIdWrapperPanel.add(jEmployeeIdLabel);
        jEmployeeIdWrapperPanel.add(jEmployeeIdSpinner);

        getContentPane().add(jEmployeeIdWrapperPanel);

        jEmployeeNameWrapperPanel.setLayout(new javax.swing.BoxLayout(jEmployeeNameWrapperPanel, javax.swing.BoxLayout.LINE_AXIS));

        jEmployeeNameLabel.setText("Nom de l'employé(e):");
        jEmployeeNameWrapperPanel.add(jEmployeeNameLabel);

        jEmployeeNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jEmployeeNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmployeeNameTextFieldActionPerformed(evt);
            }
        });
        jEmployeeNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jEmployeeNameTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jEmployeeNameTextFieldKeyReleased(evt);
            }
        });
        jEmployeeNameWrapperPanel.add(jEmployeeNameTextField);

        getContentPane().add(jEmployeeNameWrapperPanel);

        jEmployeeFirstNameWrapperPanel.setLayout(new javax.swing.BoxLayout(jEmployeeFirstNameWrapperPanel, javax.swing.BoxLayout.LINE_AXIS));

        jEmployeeFirstNameLabel.setText("Prénom de l'employé(e):");
        jEmployeeFirstNameWrapperPanel.add(jEmployeeFirstNameLabel);

        jEmployeeFirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmployeeFirstNameTextFieldActionPerformed(evt);
            }
        });
        jEmployeeFirstNameWrapperPanel.add(jEmployeeFirstNameTextField);

        getContentPane().add(jEmployeeFirstNameWrapperPanel);

        jEmployeeJobWrapperPanel.setLayout(new javax.swing.BoxLayout(jEmployeeJobWrapperPanel, javax.swing.BoxLayout.LINE_AXIS));

        jEmployeeJobLabel.setText("Poste de l'employé(e):");
        jEmployeeJobWrapperPanel.add(jEmployeeJobLabel);
        jEmployeeJobWrapperPanel.add(jEmployeeJobTextField);

        getContentPane().add(jEmployeeJobWrapperPanel);

        jEmployeeSalaryWrapperPanel.setLayout(new javax.swing.BoxLayout(jEmployeeSalaryWrapperPanel, javax.swing.BoxLayout.LINE_AXIS));

        jEmployeeSalaryLabel.setText("Salaire de l'employé(e):");
        jEmployeeSalaryWrapperPanel.add(jEmployeeSalaryLabel);
        jEmployeeSalaryWrapperPanel.add(jEmployeeSalarySpinner);

        getContentPane().add(jEmployeeSalaryWrapperPanel);

        jButtonsWrapperPanel.setLayout(new javax.swing.BoxLayout(jButtonsWrapperPanel, javax.swing.BoxLayout.LINE_AXIS));

        jEmployeeConfirmButton.setText("Confirmer");
        jEmployeeConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmployeeConfirmButtonActionPerformed(evt);
            }
        });
        jButtonsWrapperPanel.add(jEmployeeConfirmButton);

        jEmployeeResetButton.setText("Réinitialiser");
        jEmployeeResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmployeeResetButtonActionPerformed(evt);
            }
        });
        jButtonsWrapperPanel.add(jEmployeeResetButton);

        getContentPane().add(jButtonsWrapperPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEmployeeNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmployeeNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmployeeNameTextFieldActionPerformed

    private void jEmployeeFirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmployeeFirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmployeeFirstNameTextFieldActionPerformed

    private void jEmployeeResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmployeeResetButtonActionPerformed
        // TODO add your handling code here:
        jEmployeeNameTextField.setText("");
        jEmployeeFirstNameTextField.setText("");
        jEmployeeJobTextField.setText("");
        jEmployeeSalarySpinner.setValue(0);
    }//GEN-LAST:event_jEmployeeResetButtonActionPerformed
    
    private void jEmployeeConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmployeeConfirmButtonActionPerformed
        // TODO add your handling code here:
        if (!isFormLegit())
        {
            // TODO: add a popup menu
            System.out.println("The form isn't legit.");
            return;
        }
        
        Employee e = new Employee();
        
        e.setNumEmp(String.valueOf((int)jEmployeeIdSpinner.getValue()));
        e.setNom(jEmployeeNameTextField.getText());
        e.setPrenom(jEmployeeFirstNameTextField.getText());
        e.setPoste(jEmployeeJobTextField.getText());
        e.setSalaire((int)jEmployeeSalarySpinner.getValue());
        
        if (m_IsEditMode)
            DBControl.deferEmployeeController().editEntry(new Object[] { e, m_PreviousEmployeeId });
        else
            DBControl.deferEmployeeController().addEntry(e);
        
        DBControl.deferEmployeeController().reloadEntries(GPCPUi.getEmployeeTable());
        DBControl.deferPointageController().reloadEntries(GPCPUi.getPointageTable());
        DBControl.deferHolidayController().reloadEntries(GPCPUi.getHolidayTable());
        setVisible(false);
    }//GEN-LAST:event_jEmployeeConfirmButtonActionPerformed

    private void jEmployeeNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmployeeNameTextFieldKeyPressed
        // TODO add your handling code here:
        
        String empName = jEmployeeNameTextField.getText().toUpperCase();
        
        jEmployeeNameTextField.setText(empName);
    }//GEN-LAST:event_jEmployeeNameTextFieldKeyPressed

    private void jEmployeeNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmployeeNameTextFieldKeyReleased
        // TODO add your handling code here:
        System.out.println("Action performed");
        String empName = jEmployeeNameTextField.getText().toUpperCase();
        
        jEmployeeNameTextField.setText(empName);
    }//GEN-LAST:event_jEmployeeNameTextFieldKeyReleased

    public void setIsEditMode(boolean isEditMode) { this.m_IsEditMode = isEditMode; }
    public void setPreviousEmployeeId(String prevEmployeeId) {
        this.m_PreviousEmployeeId = prevEmployeeId;
    }
    public void setEmployeeId(String employeeId) {
        jEmployeeIdSpinner.setValue(Integer.parseInt(employeeId));
    }
    public void setEmployeeName(String employeeName) { 
        jEmployeeNameTextField.setText(employeeName); 
    }
    public void setEmployeeFirstName(String employeeFirstName) {
        jEmployeeFirstNameTextField.setText(employeeFirstName);
    }
    public void setEmployeeJob(String employeeJob) {
        jEmployeeJobTextField.setText(employeeJob);
    }
    public void setEmployeeSalary(int employeeSalary) {
        jEmployeeSalarySpinner.setValue(employeeSalary);
    }
    
    private boolean isNonRedundantEntry(int newNumEmp)
    {
        int prevNumEmp = (m_IsEditMode ? Integer.parseInt(m_PreviousEmployeeId) : newNumEmp);
        
        if (m_IsEditMode && prevNumEmp == newNumEmp)
            return true;
        
        return !DBControl.deferEmployeeController().entryExists(DataArg.makeDataArg(newNumEmp));
    }
    
    private boolean isFormLegit() {
        final int minimalSalary = 1;
        int employeeId = (int)jEmployeeIdSpinner.getValue();
        String employeeName = jEmployeeNameTextField.getText();
        String employeeFirstName = jEmployeeFirstNameTextField.getText();
        String employeeJob = jEmployeeJobTextField.getText();
        int employeeSalary = (int) jEmployeeSalarySpinner.getValue();
        final java.awt.Frame parent = (java.awt.Frame)getOwner();
        
        if (employeeId <= 0)
        {
            Util.invokeErrorMessage(parent, "Le numéro d'un employé doit être >= 1.");
            return false;
        }
        if (!isNonRedundantEntry(employeeId))
        {
            Util.invokeErrorMessage(parent, "Un employé avec ce numéro existe déjà.");
            return false;
        }
        if (employeeName.isEmpty())
        {
            Util.invokeErrorMessage(parent, "Le nom d'un employé ne peut pas être vide.");
            return false;
        }
        if (employeeFirstName.isEmpty())
        {
            Util.invokeErrorMessage(parent, "Le prénom de l'employé ne peut pas être vide.");
            return false;
        }
        if (employeeJob.isEmpty())
        {
            Util.invokeErrorMessage(parent, "Le poste de l'employé ne peut pas être vide.");
            return false;
        }
        if (employeeSalary < minimalSalary)
        {
            Util.invokeErrorMessage(parent, "Le salaire ne doit pas être inférieur à "
                                + String.valueOf(minimalSalary) + ".");
            return false;
        }
        
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeFormUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeFormUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeFormUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeFormUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmployeeFormUi dialog = new EmployeeFormUi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private boolean m_IsEditMode;
    private String m_PreviousEmployeeId;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jButtonsWrapperPanel;
    private javax.swing.JButton jEmployeeConfirmButton;
    private javax.swing.JLabel jEmployeeFirstNameLabel;
    private javax.swing.JTextField jEmployeeFirstNameTextField;
    private javax.swing.JPanel jEmployeeFirstNameWrapperPanel;
    private javax.swing.JLabel jEmployeeIdLabel;
    private javax.swing.JSpinner jEmployeeIdSpinner;
    private javax.swing.JPanel jEmployeeIdWrapperPanel;
    private javax.swing.JLabel jEmployeeJobLabel;
    private javax.swing.JTextField jEmployeeJobTextField;
    private javax.swing.JPanel jEmployeeJobWrapperPanel;
    private javax.swing.JLabel jEmployeeNameLabel;
    private javax.swing.JTextField jEmployeeNameTextField;
    private javax.swing.JPanel jEmployeeNameWrapperPanel;
    private javax.swing.JButton jEmployeeResetButton;
    private javax.swing.JLabel jEmployeeSalaryLabel;
    private javax.swing.JSpinner jEmployeeSalarySpinner;
    private javax.swing.JPanel jEmployeeSalaryWrapperPanel;
    // End of variables declaration//GEN-END:variables
}
