/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fnln.andy.gpcp.ui;

import fnln.andy.gpcp.DBControl;
import fnln.andy.gpcp.core.Employee;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author andy
 */
public class GPCPUi extends javax.swing.JFrame {

    /**
     * Creates new form GPCPUi
     */
    public GPCPUi() {
        initComponents();
        
        DBControl.loadEmployees(GPCPUi.jEmployeeTable);
        DBControl.loadPointages(GPCPUi.jPointageTable);
        DBControl.loadHolidays(GPCPUi.jHolidayTable);
    }
    
    public static javax.swing.JTable getEmployeeTable() { return jEmployeeTable; }
    public static javax.swing.JTable getPointageTable() { return jPointageTable; }
    public static javax.swing.JTable getHolidayTable() { return jHolidayTable; }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainTabs = new javax.swing.JTabbedPane();
        jEmployeePanel = new javax.swing.JPanel();
        jSearchBarPanel = new javax.swing.JPanel();
        jSearchEmployeeLabel = new javax.swing.JLabel();
        jSearchContentTextField = new javax.swing.JTextField();
        jEmployeeCrudPanel = new javax.swing.JPanel();
        jAddNewEmployeeButton = new javax.swing.JButton();
        jEditEmployeeButton = new javax.swing.JButton();
        jRemoveEmployeeButton = new javax.swing.JButton();
        jEmployeeScrollPane = new javax.swing.JScrollPane();
        jEmployeeTable = new javax.swing.JTable();
        jPointagePanel = new javax.swing.JPanel();
        jPointageScrollPane = new javax.swing.JScrollPane();
        jPointageTable = new javax.swing.JTable();
        jHolidayPanel = new javax.swing.JPanel();
        jHolidayScrollPane = new javax.swing.JScrollPane();
        jHolidayTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Congé(s) et de Pointage(s) du Personnel");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jEmployeePanel.setMaximumSize(new java.awt.Dimension(32767, 78));
        jEmployeePanel.setLayout(new java.awt.GridLayout(0, 1, 0, 30));

        jSearchBarPanel.setLayout(new java.awt.GridLayout(0, 2));

        jSearchEmployeeLabel.setText("Rechercher:");
        jSearchBarPanel.add(jSearchEmployeeLabel);

        jSearchContentTextField.setText("Nom(s) et Prénom(s)...");
        jSearchContentTextField.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jSearchContentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchContentTextFieldActionPerformed(evt);
            }
        });
        jSearchBarPanel.add(jSearchContentTextField);

        jEmployeePanel.add(jSearchBarPanel);

        jAddNewEmployeeButton.setText("Ajouter un employé");
        jAddNewEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddNewEmployeeButtonActionPerformed(evt);
            }
        });
        jEmployeeCrudPanel.add(jAddNewEmployeeButton);

        jEditEmployeeButton.setText("Modifier un employé");
        jEditEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditEmployeeButtonActionPerformed(evt);
            }
        });
        jEmployeeCrudPanel.add(jEditEmployeeButton);

        jRemoveEmployeeButton.setText("Retirer un employé");
        jRemoveEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveEmployeeButtonActionPerformed(evt);
            }
        });
        jEmployeeCrudPanel.add(jRemoveEmployeeButton);

        jEmployeePanel.add(jEmployeeCrudPanel);

        jEmployeeScrollPane.setMaximumSize(new java.awt.Dimension(32767, 100));

        jEmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Nom", "Prenom", "Poste", "Salaire"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jEmployeeTable.getTableHeader().setReorderingAllowed(false);
        jEmployeeScrollPane.setViewportView(jEmployeeTable);

        jEmployeePanel.add(jEmployeeScrollPane);

        jMainTabs.addTab("Employé(s)", jEmployeePanel);

        jPointagePanel.setLayout(new java.awt.GridLayout(1, 0));

        jPointageScrollPane.setMaximumSize(new java.awt.Dimension(32767, 100));

        jPointageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date de pointage", "Numéro d'employé", "Pointage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jPointageTable.getTableHeader().setReorderingAllowed(false);
        jPointageScrollPane.setViewportView(jPointageTable);

        jPointagePanel.add(jPointageScrollPane);

        jMainTabs.addTab("Pointage(s)", jPointagePanel);

        jHolidayPanel.setLayout(new java.awt.GridLayout(1, 0));

        jHolidayScrollPane.setMaximumSize(new java.awt.Dimension(32767, 100));

        jHolidayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro de congé", "Numéro d'employé", "Motif", "Nombre de jours", "Date de demande", "Date de retour"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jHolidayScrollPane.setViewportView(jHolidayTable);

        jHolidayPanel.add(jHolidayScrollPane);

        jMainTabs.addTab("Congé(s)", jHolidayPanel);

        getContentPane().add(jMainTabs);
        jMainTabs.getAccessibleContext().setAccessibleName("employeeTab");
        jMainTabs.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchContentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchContentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchContentTextFieldActionPerformed

    private void jAddNewEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddNewEmployeeButtonActionPerformed
        // TODO add your handling code here:
        EmployeeFormUi ui = new EmployeeFormUi(this, true);
        
        ui.setIsEditMode(false);
        ui.setTitle("Ajouter un nouvel employé");
        SwingUtilities.invokeLater(() -> {
            ui.setVisible(true);
        });
    }//GEN-LAST:event_jAddNewEmployeeButtonActionPerformed

    private void jEditEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditEmployeeButtonActionPerformed
        // TODO add your handling code here:
        final int selectedEmployeeIndex = jEmployeeTable.getSelectedRow();
        
        if (selectedEmployeeIndex == -1)
        {
            // TODO: add a popup menu for no selected index
            System.out.println("No selected employee.");
            return;
        }
        
        TableModel employeeTableModel = jEmployeeTable.getModel();
        
        if (!(employeeTableModel instanceof DefaultTableModel))
        {
            return;
        }
        
        DefaultTableModel defaultTM = (DefaultTableModel)(employeeTableModel);
        Employee selectedEmployee = new Employee();
        
        selectedEmployee.setNumEmp((String)(defaultTM.getValueAt(selectedEmployeeIndex, 0)));
        selectedEmployee.setNom((String)(defaultTM.getValueAt(selectedEmployeeIndex, 1)));
        selectedEmployee.setPrenom((String)(defaultTM.getValueAt(selectedEmployeeIndex, 2)));
        selectedEmployee.setPoste((String)(defaultTM.getValueAt(selectedEmployeeIndex, 3)));
        selectedEmployee.setSalaire((int)(defaultTM.getValueAt(selectedEmployeeIndex, 4)));
        
        EmployeeFormUi ui = new EmployeeFormUi(this, true);
        
        ui.setIsEditMode(true);
        ui.setPreviousEmployeeId(selectedEmployee.getNumEmp());
        ui.setEmployeeId(selectedEmployee.getNumEmp());
        ui.setEmployeeName(selectedEmployee.getNom());
        ui.setEmployeeFirstName(selectedEmployee.getPrenom());
        ui.setEmployeeJob(selectedEmployee.getPoste());
        ui.setEmployeeSalary(selectedEmployee.getSalaire());
        ui.setTitle("Modifier l'employé: " + selectedEmployee.getPrintable());
        
        SwingUtilities.invokeLater(() -> {
            ui.setVisible(true);
        });
    }//GEN-LAST:event_jEditEmployeeButtonActionPerformed

    private void jRemoveEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveEmployeeButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jEmployeeTable.getSelectedRow();
        
        if (selectedIndex == -1)
        {
            // TODO: add a popup window
            System.out.println("No employee row selected for deletion.");
            return;
        }
        
        TableModel tm = jEmployeeTable.getModel();
        
        if (!(tm instanceof DefaultTableModel))
        {
            System.out.println("The table model isn't a DefaultTableModel.");
            return;
        }
        
        DefaultTableModel defaultTM = (DefaultTableModel)(tm);
        
        DBControl.deleteEmployee((String)defaultTM.getValueAt(selectedIndex, 0));
    }//GEN-LAST:event_jRemoveEmployeeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPCPUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPCPUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPCPUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPCPUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GPCPUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddNewEmployeeButton;
    private javax.swing.JButton jEditEmployeeButton;
    private javax.swing.JPanel jEmployeeCrudPanel;
    private javax.swing.JPanel jEmployeePanel;
    private javax.swing.JScrollPane jEmployeeScrollPane;
    private static javax.swing.JTable jEmployeeTable;
    private javax.swing.JPanel jHolidayPanel;
    private javax.swing.JScrollPane jHolidayScrollPane;
    private static javax.swing.JTable jHolidayTable;
    private javax.swing.JTabbedPane jMainTabs;
    private javax.swing.JPanel jPointagePanel;
    private javax.swing.JScrollPane jPointageScrollPane;
    private static javax.swing.JTable jPointageTable;
    private javax.swing.JButton jRemoveEmployeeButton;
    private javax.swing.JPanel jSearchBarPanel;
    private javax.swing.JTextField jSearchContentTextField;
    private javax.swing.JLabel jSearchEmployeeLabel;
    // End of variables declaration//GEN-END:variables
}
