/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package fnln.andy.gpcp.ui;

import fnln.andy.gpcp.inputverifiers.DayInDateInputVerifier;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JSpinner;

/**
 *
 * @author andy
 */
public class PointageFormUi extends javax.swing.JDialog {

    /**
     * Creates new form PointageFormUi
     */
    public PointageFormUi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePointageLabel = new javax.swing.JLabel();
        jDatePointagePanel = new javax.swing.JPanel();
        jDatePointageDayLabel = new javax.swing.JLabel();
        jDatePointageMonthLabel = new javax.swing.JLabel();
        jDatePointageYearLabel = new javax.swing.JLabel();
        jDatePointageDaySpinner = new javax.swing.JSpinner();
        jDatePointageMonthComboBox = new javax.swing.JComboBox<>();
        jDatePointageYearSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDatePointageLabel.setText("jLabel1");

        jDatePointagePanel.setLayout(new java.awt.GridLayout(0, 3, 4, 0));

        jDatePointageDayLabel.setText("Jour");
        jDatePointagePanel.add(jDatePointageDayLabel);

        jDatePointageMonthLabel.setText("Mois");
        jDatePointagePanel.add(jDatePointageMonthLabel);

        jDatePointageYearLabel.setText("Année");
        jDatePointagePanel.add(jDatePointageYearLabel);

        jDatePointageDaySpinner.setValue(1);
        jDatePointageDaySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jDatePointageDaySpinnerStateChanged(evt);
            }
        });
        jDatePointagePanel.add(jDatePointageDaySpinner);

        jDatePointageMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janvier", "Fervrier", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre" }));
        jDatePointageMonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatePointageMonthComboBoxActionPerformed(evt);
            }
        });
        jDatePointagePanel.add(jDatePointageMonthComboBox);

        jDatePointageYearSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jDatePointageYearSpinnerStateChanged(evt);
            }
        });
        jDatePointagePanel.add(jDatePointageYearSpinner);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jDatePointageLabel)
                .addGap(205, 205, 205)
                .addComponent(jDatePointagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDatePointagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDatePointageLabel))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDatePointageDaySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jDatePointageDaySpinnerStateChanged
        // TODO add your handling code here:
        int currentMonth = jDatePointageMonthComboBox.getSelectedIndex();
        int currentYear = (int)jDatePointageYearSpinner.getValue();
        
        DayInDateInputVerifier.validateSpinnerValue(currentMonth, currentYear, jDatePointageDaySpinner);
    }//GEN-LAST:event_jDatePointageDaySpinnerStateChanged

    private void jDatePointageYearSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jDatePointageYearSpinnerStateChanged
        // TODO add your handling code here:
        jDatePointageDaySpinnerStateChanged(evt);
    }//GEN-LAST:event_jDatePointageYearSpinnerStateChanged

    private void jDatePointageMonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatePointageMonthComboBoxActionPerformed
        // TODO add your handling code here:
        jDatePointageDaySpinnerStateChanged(null);
    }//GEN-LAST:event_jDatePointageMonthComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PointageFormUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PointageFormUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PointageFormUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PointageFormUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PointageFormUi dialog = new PointageFormUi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDatePointageDayLabel;
    private javax.swing.JSpinner jDatePointageDaySpinner;
    private javax.swing.JLabel jDatePointageLabel;
    private javax.swing.JComboBox<String> jDatePointageMonthComboBox;
    private javax.swing.JLabel jDatePointageMonthLabel;
    private javax.swing.JPanel jDatePointagePanel;
    private javax.swing.JLabel jDatePointageYearLabel;
    private javax.swing.JSpinner jDatePointageYearSpinner;
    // End of variables declaration//GEN-END:variables
}
