/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package fnln.andy.gpcp.ui;

import fnln.andy.gpcp.core.Employee;
import fnln.andy.gpcp.inputverifiers.DayInDateInputVerifier;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JSpinner;

/**
 *
 * @author andy
 */
public class PointageFormUi extends javax.swing.JDialog {

    /**
     * Creates new form PointageFormUi
     */
    public PointageFormUi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void initEmployeeData(List<Employee> employees)
    {
        ComboBoxModel<String> numEmpCBM = jNumEmpComboBox.getModel();
        ComboBoxModel<String> empNameCBM = jEmployeeNameComboBox.getModel();
        
        if ((!(numEmpCBM instanceof DefaultComboBoxModel)) ||
             !(empNameCBM instanceof DefaultComboBoxModel))
            return;
        
        DefaultComboBoxModel<String> numEmpCBDefaultM = (DefaultComboBoxModel<String>)(numEmpCBM);
        DefaultComboBoxModel<String> empNameCBDefaultM = (DefaultComboBoxModel<String>)(empNameCBM);
        
        for (Employee e : employees) {
            numEmpCBDefaultM.addElement(e.getNumEmp());
            empNameCBDefaultM.addElement(e.getNom() + " " + e.getPrenom());
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePointageLabel = new javax.swing.JLabel();
        jDatePointagePanel = new javax.swing.JPanel();
        jDatePointageDayLabel = new javax.swing.JLabel();
        jDatePointageMonthLabel = new javax.swing.JLabel();
        jDatePointageYearLabel = new javax.swing.JLabel();
        jDatePointageDaySpinner = new javax.swing.JSpinner();
        jDatePointageMonthComboBox = new javax.swing.JComboBox<>();
        jDatePointageYearSpinner = new javax.swing.JSpinner();
        jNumEmpLabel = new javax.swing.JLabel();
        jNumEmpPanel = new javax.swing.JPanel();
        jNumEmpComboBox = new javax.swing.JComboBox<>();
        jEmployeeNameComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDatePointageLabel.setText("Date de pointage:");

        jDatePointagePanel.setLayout(new java.awt.GridLayout(0, 3, 4, 0));

        jDatePointageDayLabel.setText("Jour");
        jDatePointagePanel.add(jDatePointageDayLabel);

        jDatePointageMonthLabel.setText("Mois");
        jDatePointagePanel.add(jDatePointageMonthLabel);

        jDatePointageYearLabel.setText("Année");
        jDatePointagePanel.add(jDatePointageYearLabel);

        jDatePointageDaySpinner.setValue(1);
        jDatePointageDaySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jDatePointageDaySpinnerStateChanged(evt);
            }
        });
        jDatePointagePanel.add(jDatePointageDaySpinner);

        jDatePointageMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janvier", "Fervrier", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre" }));
        jDatePointageMonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatePointageMonthComboBoxActionPerformed(evt);
            }
        });
        jDatePointagePanel.add(jDatePointageMonthComboBox);

        jDatePointageYearSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jDatePointageYearSpinnerStateChanged(evt);
            }
        });
        jDatePointagePanel.add(jDatePointageYearSpinner);

        jNumEmpLabel.setText("Numéro d'employé:");

        javax.swing.GroupLayout jNumEmpPanelLayout = new javax.swing.GroupLayout(jNumEmpPanel);
        jNumEmpPanel.setLayout(jNumEmpPanelLayout);
        jNumEmpPanelLayout.setHorizontalGroup(
            jNumEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNumEmpPanelLayout.createSequentialGroup()
                .addComponent(jNumEmpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNumEmpPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jEmployeeNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jNumEmpPanelLayout.setVerticalGroup(
            jNumEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNumEmpPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jNumEmpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEmployeeNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNumEmpLabel)
                        .addGap(96, 96, 96)
                        .addComponent(jNumEmpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDatePointageLabel)
                        .addGap(182, 182, 182)
                        .addComponent(jDatePointagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDatePointagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDatePointageLabel))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNumEmpLabel)
                    .addComponent(jNumEmpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDatePointageDaySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jDatePointageDaySpinnerStateChanged
        // TODO add your handling code here:
        int currentMonth = jDatePointageMonthComboBox.getSelectedIndex();
        int currentYear = (int)jDatePointageYearSpinner.getValue();
        
        DayInDateInputVerifier.validateSpinnerValue(currentMonth, currentYear, jDatePointageDaySpinner);
    }//GEN-LAST:event_jDatePointageDaySpinnerStateChanged

    private void jDatePointageYearSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jDatePointageYearSpinnerStateChanged
        // TODO add your handling code here:
        jDatePointageDaySpinnerStateChanged(evt);
    }//GEN-LAST:event_jDatePointageYearSpinnerStateChanged

    private void jDatePointageMonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatePointageMonthComboBoxActionPerformed
        // TODO add your handling code here:
        jDatePointageDaySpinnerStateChanged(null);
    }//GEN-LAST:event_jDatePointageMonthComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PointageFormUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PointageFormUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PointageFormUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PointageFormUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PointageFormUi dialog = new PointageFormUi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDatePointageDayLabel;
    private javax.swing.JSpinner jDatePointageDaySpinner;
    private javax.swing.JLabel jDatePointageLabel;
    private javax.swing.JComboBox<String> jDatePointageMonthComboBox;
    private javax.swing.JLabel jDatePointageMonthLabel;
    private javax.swing.JPanel jDatePointagePanel;
    private javax.swing.JLabel jDatePointageYearLabel;
    private javax.swing.JSpinner jDatePointageYearSpinner;
    private javax.swing.JComboBox<String> jEmployeeNameComboBox;
    private javax.swing.JComboBox<String> jNumEmpComboBox;
    private javax.swing.JLabel jNumEmpLabel;
    private javax.swing.JPanel jNumEmpPanel;
    // End of variables declaration//GEN-END:variables
}
